# Generated by Django 4.2 on 2026-08-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO 3166-1 alpha-2, ex: BF', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dial_code', models.CharField(help_text='Ex: +226', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('catalog_version', models.PositiveIntegerField(default=1, help_text="Incrémenté à chaque changement d'un opérateur/type/pattern de ce pays — sert au resync mobile (ETag).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operators/logos/')),
                ('sms_sender', models.CharField(blank=True, help_text="Expéditeur SMS tel qu'il apparaît sur l'appareil, ex: OrangeMoney", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='catalog.country')),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperatorTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ussd_code', models.CharField(blank=True, max_length=100)),
                ('commission_taux', models.DecimalField(decimal_places=3, default=0, help_text="Taux de commission en %, un seul taux par type (D9 — sens non pris en compte pour l'instant)", max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_types', to='catalog.operator')),
            ],
            options={
                'verbose_name': 'Type activé par opérateur',
                'verbose_name_plural': 'Types activés par opérateur',
                'ordering': ['operator', 'transaction_type'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant stable, ex: deposit, transfert, paiement_marchand', unique=True)),
                ('label', models.CharField(max_length=100)),
                ('default_direction', models.CharField(choices=[('in', 'Entrant'), ('out', 'Sortant')], help_text='Sens par défaut — peut être surchargé par un SmsPattern spécifique', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de transaction',
                'verbose_name_plural': 'Types de transaction',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SmsPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_example', models.TextField(help_text='Exemple de SMS réel (anonymisé si besoin)')),
                ('tagged_zones', models.JSONField(help_text='Liste de {start, end, fieldName} — mêmes noms de champs que TaggedZone côté mobile')),
                ('direction_override', models.CharField(blank=True, choices=[('in', 'Entrant'), ('out', 'Sortant')], help_text="Si renseigné, prime sur le sens par défaut du type (D1) — ex: 'Transfert reçu' vs 'Transfert envoyé'", max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator_transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_patterns', to='catalog.operatortransactiontype')),
            ],
            options={
                'verbose_name': 'Pattern SMS',
                'verbose_name_plural': 'Patterns SMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='operatortransactiontype',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_links', to='catalog.transactiontype'),
        ),
        migrations.AlterUniqueTogether(
            name='operatortransactiontype',
            unique_together={('operator', 'transaction_type')},
        ),
    ]
