# Generated by Django 4.2 on 2026-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smspattern',
            name='cible_compte',
            field=models.CharField(choices=[('tous', 'Tous'), ('particulier', 'Particulier'), ('agence', 'Agence')], default='tous', help_text="Le SMS d'un compte Particulier diffère souvent de celui d'un compte Agence pour la même transaction — ce champ cible le pattern en conséquence.", max_length=12),
        ),
    ]
