# Generated by Django 4.2 on 2026-08-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_smspattern_cible_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operators', to='catalog.country'),
        ),
        migrations.AlterField(
            model_name='operatortransactiontype',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operator_types', to='catalog.operator'),
        ),
        migrations.AlterField(
            model_name='operatortransactiontype',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operator_links', to='catalog.transactiontype'),
        ),
        migrations.AlterField(
            model_name='smspattern',
            name='operator_transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sms_patterns', to='catalog.operatortransactiontype'),
        ),
    ]
