# Generated by Django 4.2 on 2026-08-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licences', '0005_alter_achathistorique_client_alter_agence_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur_telephone', models.CharField(max_length=20)),
                ('demandeur_device_id', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agence', models.ForeignKey(blank=True, help_text="Assignée par le patron au moment de l'approbation", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='affiliations', to='licences.agence')),
                ('patron', models.ForeignKey(help_text='Compte propriétaire des agences (identifié par son numéro)', on_delete=django.db.models.deletion.RESTRICT, related_name='demandes_affiliation_recues', to='licences.client')),
            ],
            options={
                'verbose_name': "Demande d'affiliation",
                'verbose_name_plural': "Demandes d'affiliation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(help_text='id local (mobile) de la transaction', max_length=64)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('transaction_type_code', models.CharField(blank=True, max_length=50)),
                ('transaction_type_label', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(blank=True, max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('transaction_created_at', models.DateTimeField(help_text='created_at côté mobile')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='synced_transactions', to='licences.agence')),
            ],
            options={
                'verbose_name': 'Transaction synchronisée',
                'verbose_name_plural': 'Transactions synchronisées',
                'ordering': ['-transaction_created_at'],
                'unique_together': {('agence', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('client_created_at', models.DateTimeField(help_text='created_at côté mobile')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='synced_clients', to='licences.agence')),
            ],
            options={
                'verbose_name': 'Client synchronisé',
                'verbose_name_plural': 'Clients synchronisés',
                'ordering': ['-client_created_at'],
                'unique_together': {('agence', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncedCaisseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=64)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('operation_created_at', models.DateTimeField(help_text='created_at côté mobile')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='synced_caisse_operations', to='licences.agence')),
            ],
            options={
                'verbose_name': 'Opération caisse synchronisée',
                'verbose_name_plural': 'Opérations caisse synchronisées',
                'ordering': ['-operation_created_at'],
                'unique_together': {('agence', 'local_id')},
            },
        ),
    ]
