# Generated by Django 4.2 on 2026-04-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Numéro BF ex: 70123456', max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: MT-A3F9-KL82MN7P20260330', max_length=100, unique=True)),
                ('device_id', models.CharField(help_text="Identifiant unique de l'appareil", max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_mois', models.IntegerField(help_text='1, 12, ou 24 mois')),
                ('montant_paye', models.IntegerField(default=0, help_text='Montant en FCFA')),
                ('statut', models.CharField(choices=[('essai', 'Essai gratuit'), ('active', 'Active'), ('expiree', 'Expirée'), ('suspendue', 'Suspendue')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='licences.client')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('device_id', models.CharField(max_length=200)),
                ('duree_mois', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Note admin (référence paiement, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.licence')),
            ],
            options={
                'verbose_name': "Demande d'activation",
                'verbose_name_plural': "Demandes d'activation",
                'ordering': ['-created_at'],
            },
        ),
    ]
