# Generated by Django 4.2 on 2026-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cible', models.CharField(choices=[('all', 'Tous les utilisateurs'), ('individual', 'Un utilisateur'), ('group', 'Un groupe')], default='all', max_length=20)),
                ('telephones', models.TextField(blank=True, help_text='Téléphone(s) cible. Vide = tout le monde.')),
                ('lu_par', models.TextField(blank=True, default='', help_text='Téléphones ayant lu la notif (séparés par virgule)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
