# Generated by Django 4.2 on 2026-04-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('active', 'Activé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('montant_paye', models.IntegerField(default=2000)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_historique', to='licences.client')),
            ],
            options={
                'verbose_name': 'Achat Historique SMS',
                'verbose_name_plural': 'Achats Historique SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
