# Generated by Django 4.2 on 2026-08-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0004_agences_pricing_multiagence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achathistorique',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='achats_historique', to='licences.client'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agences', to='licences.client'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='licences', to='licences.agence'),
        ),
    ]
