# Generated by Django 4.2 on 2026-08-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0005_alter_achathistorique_client_alter_agence_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password_hash',
            field=models.CharField(blank=True, help_text="Hash (django.contrib.auth.hashers) du mot de passe compte — D13, permet une connexion instantanée depuis un nouvel appareil sans passer par l'affiliation/approbation (sync.AffiliationRequest). Nullable pour les comptes créés avant l'introduction du mot de passe ; obligatoire pour tout nouveau compte (imposé côté mobile).", max_length=128, null=True),
        ),
    ]
